### ISSUE TITLE
Crashing when used with Roughly Enough Items

### ISSUE THREAD

**Issue by BurgerLUA** [NerdHubMC/Refined-Machinery#47] opened 2019-06-14 08:02 UTC
Upon clicking dust in any recipe with Roughly Enough Items , the client crashes with log error

```
Description: mouseClicked event handler

java.lang.ClassCastException: abused_master.refinedmachinery.registry.PulverizerRecipes$PulverizerRecipe cannot be cast to net.minecraft.class_1860
```

Log: https://paste.ee/p/MbfXP

It happens with no other craftable object, only the dust.

**Comment by shedaniel** [comment] 2019-06-14 11:31
Duplicate of #40 and #42 and apparently REI didn't fix this correctly (REI should be able to catch the error, print the track trace and not crash), and I forgot to claim in REI that if the recipe type doesn't extend `Recipe<?>`, [these lines](https://github.com/NerdHubMC/Refined-Machinery/blob/f8d4ac87a15ead0776d699886b218629c77796a2/src/main/java/abused_master/refinedmachinery/rei/plugin/PulverizerDisplay.java#L23-L26) should return an empty optional (https://github.com/shedaniel/RoughlyEnoughItems/blob/5e9a5691c42b535eb9bb410fe366edfbae93192d/src/main/java/me/shedaniel/rei/api/RecipeDisplay.java#L18-L21).

**Comment by robmctouche** [comment] 2019-06-14 14:25
How would i fix this issue >?

**Comment by UpcraftLP** [comment] 2019-06-14 20:24
> How would i fix this issue >?

by updating your REI version.

**Closed as completed by UpcraftLP** 2019-06-14 20:24 UTC
Labels: duplicate
