### ISSUE TITLE
Game crashing when I add Refined-Machinery to mod folder (see logs)

### ISSUE THREAD

**Issue by CarlucciMods** [NerdHubMC/Refined-Machinery#62] opened 2019-12-08 22:12 UTC
I have tested each mod collectively and individually and only when i add  your mod, any version to the mod folder i get a crash. Maybe its not playing nice with something else.

Running Fabric 0.7.2 build 174- 1. 14. 4, 10Gig of memory allocated. This is my last hurtle.

[crash-2019-12-08_17.05.17-client.txt](https://github.com/NerdHubMC/Refined-Machinery/files/3937232/crash-2019-12-08_17.05.17-client.txt)
[Log 1.txt](https://github.com/NerdHubMC/Refined-Machinery/files/3937233/Log.1.txt)

**Comment by alothmanmoe** [comment] 2019-12-08 23:40
This is actually caused by optifine, not Refined Machinery, also i no longer dev for mc so no further updates for my mods will be released. Not by me at least

**Closed as completed by alothmanmoe** 2019-12-08 23:40 UTC
