### ISSUE TITLE
1.14.2 Refined Machinery 1.1.0_1.14.1-Fabric(steel ingot not charging)

### ISSUE THREAD

**Issue by SDUBZ** [NerdHubMC/Refined-Machinery#33] opened 2019-05-30 04:29 UTC
when i put steel in charger it doesnt put any energy into ingot but drains all the energy out of chrager

**Comment by Napkin** [comment] 2019-05-30 19:01
It works for me in a single-player world but not on a dedicated server.

**Comment by Napkin** [comment] 2019-05-30 19:02
This is probably a duplicate of https://github.com/NerdHubMC/Refined-Machinery/issues/23.

**Closed as completed** 2019-06-01 00:51 UTC
Labels: bug, duplicate
